import { adrUrl } from '@/help/adr';
import type { HelpTopic } from '@/help/types';

/**
 * `Invoices/Show` — specs.md §12.1 (US-BILL-01/02, BR-BILL-01/02), plan §11 (Faza 5,
 * lotul A). Reconciliat cu codul la 2026-09-20: `InvoiceController`
 * (`CreateInvoiceAction`, `MarkInvoiceSentAction`, `VoidInvoiceAction`),
 * `PaymentController` (`RegisterPaymentAction`), `InvoicePolicy`/`PaymentPolicy`,
 * `GenerateInvoicePdfJob` (ADR-013), `MarkOverdueInvoicesJob` (BR-BILL-02).
 */
const invoiceDetail: HelpTopic = {
    id: 'invoice-detail',
    title: 'Invoice detail',
    whatIsThis:
        "This is one invoice's full record — its status, issue and due dates, totals, every payment recorded against it, and the PDF generated from it. It always traces back to exactly one order.",
    whatCanYouDo: [
        'On the source order\'s page, "Create Invoice" once it\'s confirmed or fulfilled — this is the only way to reach this page for a new invoice.',
        '"Mark as sent" once the invoice looks right — this locks in the due date from the account\'s credit terms.',
        'Record a payment (amount, method, and the date it was received) against a sent or overdue invoice — a full payment marks it "Paid" automatically.',
        '"Void" an invoice from any status except one that is already void, with a required reason — anyone who opens it later sees exactly why.',
        'Download the PDF once it says "ready", or "Retry" if it says it failed to generate.',
    ],
    rules: [
        'An invoice can only be created from an order that is confirmed or fulfilled, and only if it doesn\'t already have one — voiding an invoice frees the order for a new one, but the voided one stays on record with its own payment history.',
        "Once an invoice leaves \"draft\" it can no longer be edited — the only way forward is Void and a fresh invoice, never a silent correction (BR-BILL-01).",
        "A payment can never push the balance below zero: it's capped at what's still owed at the moment you submit it, checked again on the server in case another payment landed first.",
        'A payment can only be recorded on a sent or overdue invoice — never on a draft (nothing has been billed yet) or an already-paid or voided one.',
        'An invoice moves to "Overdue" on its own, once a day, the first time its due date has passed with a balance still owed — nobody sets that status by hand.',
        'The invoice number is unique per workspace and assigned only when the invoice is created — the same locking pattern as the order number, so two invoices created at the same moment never collide.',
        'The PDF is never generated while you wait: the invoice starts as "Generating PDF…" and the page updates itself automatically until it says "ready" (with a download link) or "failed" (with a reason and a retry button).',
        'An Agent can view the invoices of the orders they own, but can never send, void, retry a PDF or record a payment — that stays with Owner and Manager on every invoice, not just their own.',
    ],
    howItsBuilt: {
        summary:
            'The invoice number is generated by locking the workspace\'s own row for the duration of creation — the exact same pattern already used for the order number (`App\\Actions\\Orders\\ConfirmOrderAction`), reused deliberately rather than reinvented, down to the `for no key update` lock and why it has to be that one, not `for update`. Recording a payment locks the invoice row itself instead (it\'s the row actually being changed, not a shared parent), so two payments racing on the same invoice are serialized without blocking anything else. The PDF is rendered by DomPDF, in the same background worker as every other PDF in this project, chosen explicitly per call rather than through the package\'s own default — the production image has no Chromium to fall back on.',
        adr: {
            id: 'ADR-013',
            title: 'External calls leave the HTTP request and move to queues',
            url: adrUrl('ADR-013', 'apeluri-externe-in-cozi'),
        },
    },
};

export default invoiceDetail;
