import { adrUrl } from '@/help/adr';
import type { HelpTopic } from '@/help/types';

/**
 * `Orders/Show`, `Orders/Create`, `Orders/Edit` — specs.md §11.2/§11.3/§11.4 (US-ORD-01,
 * BR-ORD-01/02, BR-STOCK-04), plan §9 task 2-4.
 *
 * Reconciliat cu codul la 2026-09-14: `OrderController` (draft + linii), `ConfirmOrderController`
 * (`ConfirmOrderAction`), `CancelOrderController` (`CancelOrderAction`), `OrderPolicy`
 * (Agent doar pe comenzile proprii, editare/ștergere doar pe `draft`), `App\Enums\OrderStatus`
 * (mașina de stări, un singur loc).
 */
const orderDetail: HelpTopic = {
    id: 'order-detail',
    title: 'Order detail',
    whatIsThis:
        "This is one order's full record — its account, its lines, its running totals, and where it stands: draft, confirmed, or cancelled. Creating and editing a draft use the same fields.",
    whatCanYouDo: [
        'On "New order", pick the "Account" by searching its name, then add lines by searching a variant by SKU or product name and a quantity.',
        'Change the account, contact, notes and lines with "Edit" while the order is still a draft, then "Save changes".',
        'See "Available" next to each line as you type a quantity — it is on-hand stock minus what other confirmed orders already reserved, not just on-hand.',
        '"Confirm order" once the order has at least one line — this locks in an order number and reserves the stock for every line.',
        '"Cancel" a draft at any time, or a confirmed order as long as nothing has shipped yet.',
    ],
    rules: [
        "An order has no order number while it's a draft — it gets one, sequential for this workspace, only at confirmation, so abandoned drafts never leave a gap in the numbering (BR-ORD-02).",
        'Confirming validates at least one line and reserves that quantity per line; it never touches on-hand stock, since nothing has physically left the warehouse yet — only "reserved" changes.',
        'If a line asks for more than what\'s available, confirming is not silently blocked nor silently allowed: you have to explicitly acknowledge the order will ship as a backorder (BR-STOCK-04), and the server checks that acknowledgement itself, not just the button.',
        "Editing lines only works on a draft — once an order is confirmed, its lines are locked (same rule as an issued invoice), and the only way forward is Cancel.",
        "A confirmed order can still be cancelled as long as nothing has shipped; that releases the reserved stock. Once at least one shipment exists, only its own unshipped lines can be cancelled — full cancellation is refused (BR-ORD-01).",
        'An Agent can view every order in the workspace, but only edits, confirms or cancels the ones they own; Owner and Manager can do both on any order.',
    ],
    howItsBuilt: {
        summary:
            "Every legal transition (draft → confirmed, draft/confirmed → cancelled, and the confirmed → partially_fulfilled → fulfilled path that ships once shipments exist) lives in exactly one place, `App\\Enums\\OrderStatus::canTransitionTo()` — so the fulfillment states can be switched on later without touching the rule itself. The order number is generated by locking the workspace's own row for the duration of the confirmation, the same pattern already used to keep a single \"primary contact\" per account: two confirmations racing each other serialize on that lock instead of computing the same next number twice. The shipping carrier interface (`ShippingCarrier`) and its no-external-call `DemoShippingCarrier` implementation are built now, as a permanent adapter — not a placeholder — so a real carrier can be added later without changing anything else.",
        adr: {
            id: 'ADR-010',
            title: 'Multiple shipping carriers, selectable per tenant — the interface exists before the second real adapter does',
            url: adrUrl('ADR-010', 'doi-furnizori-curierat-configurabili'),
        },
    },
};

export default orderDetail;
